// src/lib/NavItems.js
import React from "react";
import { generatePath } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";

export function useNavItems() {
    const { user } = useAuth();

    const myPageTo = user
        ? generatePath("/mypage/:userId", { userId: user.id })
        : "/mypage";

    const myPostsTo = user
        ? generatePath("/post/mypost/:userId", { userId: user.id })
        : "/login";

    const createTo = user ? "/post/create" : "/login";

    return React.useMemo(() => ([
        {
            to: "/",
            label: "Home",
            showInNav: false,
            // navLabel: "홈페이지",   // Nav 전용 (없으면 label 사용)
            header: {
                byScreen: {
                    mobile: {
                        showLogo: true,
                        showHamburger: true,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: "회원가입",
                        showButtonTitle: ({ user }) => !user,
                        showProfile: ({ user }) => !!user,
                    },
                    tablet: {
                        showLogo: true,
                        showHamburger: true,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showButtonTitle: ({ user }) => !user,
                        showProfile: ({ user }) => !!user,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: true,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showButtonTitle: ({ user }) => !user,
                        showProfile: true,
                    },
                },
            },
        },
        {
            to: "/register",
            label: "회원가입",
            showInNav: false,
            header: {
                showButtonTitle: ({ user }) => false,
                byScreen: {
                    mobile: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: "회원가입",
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showProfile: false,
                    },
                },
            },
        },
        {
            to: "/register/success",
            label: "회원가입 완료",
            showInNav: false,
            header: {
                showButtonTitle: ({ user }) => false,
                byScreen: {
                    mobile: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: "회원가입",
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showProfile: false,
                    },
                },
            },
        },
        {
            to: "/login",
            label: "로그인",
            showInNav: false,
            header: {
                byScreen: {
                    mobile: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                },
            },
        },
        {
            to: "/login/find-password",
            label: "비밀번호 찾기",
            showInNav: false,
            header: {
                showButtonTitle: ({ user }) => false,
                byScreen: {
                    mobile: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: "회원가입",
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showProfile: false,
                    },
                },
            },
        },
        {
            to: myPageTo,
            label: "마이페이지",
            showInNav: false,
            header: {
                byScreen: {
                    mobile: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: true,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: "회원가입/로그인",
                        showButtonTitle: ({ user }) => !user,
                        showProfile: false,
                    },
                },
            },
        },
        {
            to: createTo,
            label: "요리모임 등록하기",
            showInNav: true,
            header: {
                byScreen: {
                    mobile: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                },
            },
        },
        {
            to: myPostsTo,
            label: "작성한 모임",
            showInNav: true,
            header: {
                byScreen: {
                    mobile: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                },
            },
        },
        {
            to: "/post/detail/:postId",
            label: "모임 상세페이지",
            showInNav: false,
            header: {
                byScreen: {
                    mobile: {
                        showLogo: false,
                        showHamburger: true,
                        showBack: true,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: false,
                        showHamburger: true,
                        showBack: true,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: true,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                },
            },
        },
        {
            to: "/post/edit/:postId",
            label: "모임 수정하기",
            showInNav: false,
            header: {
                byScreen: {
                    mobile: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    tablet: {
                        showLogo: false,
                        showHamburger: false,
                        showBack: true,
                        showNav: false,
                        showTitle: true,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                    desktop: {
                        showLogo: true,
                        showHamburger: false,
                        showBack: false,
                        showNav: false,
                        showTitle: false,
                        Icon2Name: null,
                        buttonTitle: null,
                        showProfile: false,
                    },
                },
            },
        },
    ]), [user, myPageTo, myPostsTo]);
}
