export const NAV_ITEMS = [
    {
        to: "/",
        label: "Home",
        header: {
            byScreen: {
                mobile: { 
                    showLogo: true,
                    showHamburger: true,
                    showBack: false,
                    showNav: false,
                    showTitle: false,
                    Icon2Name: null,
                    buttonTitle: "회원가입",
                    showButtonTitle: ({ user }) => !user,
                },
                tablet: { 
                    showLogo: true,
                    showHamburger: true,
                    showBack: false,
                    showNav: false,
                    showTitle: false,
                    Icon2Name: null,
                    buttonTitle: "회원가입/로그인",
                    showButtonTitle: ({ user }) => !user,
                },
                desktop: { 
                    showLogo: true,
                    showHamburger: false,
                    showBack: false,
                    showNav: true,
                    showTitle: false,
                    Icon2Name: null,
                    buttonTitle: "회원가입/로그인",
                    showButtonTitle: ({ user }) => !user,
                },
            },
        },
    },
    {
        to: "/register",
        label: "회원가입",
        header: {
            showButtonTitle: ({ user }) => false,
            byScreen: {
                mobile: { 
                    showLogo: false,
                    showHamburger: false,
                    showBack: true,
                    showNav: false,
                    showTitle: true,
                    Icon2Name: null,
                    buttonTitle: "회원가입",
                },
                tablet: { 
                    showLogo: false,
                    showHamburger: false,
                    showBack: true,
                    showNav: false,
                    showTitle: true,
                    Icon2Name: null,
                    buttonTitle: "회원가입/로그인",
                },
                desktop: { 
                    showLogo: true,
                    showHamburger: false,
                    showBack: false,
                    showNav: false,
                    showTitle: false,
                    Icon2Name: null,
                    buttonTitle: "회원가입/로그인",
                },
            },
        },
    },
    {
        to: "/register/success",
        label: "회원가입 완료",
        header: {
            showButtonTitle: ({ user }) => false,
            byScreen: {
                mobile: { 
                    showLogo: false,
                    showHamburger: false,
                    showBack: true,
                    showNav: false,
                    showTitle: true,
                    Icon2Name: null,
                    buttonTitle: "회원가입",
                },
                tablet: { 
                    showLogo: false,
                    showHamburger: false,
                    showBack: true,
                    showNav: false,
                    showTitle: true,
                    Icon2Name: null,
                    buttonTitle: "회원가입/로그인",
                },
                desktop: { 
                    showLogo: true,
                    showHamburger: false,
                    showBack: false,
                    showNav: false,
                    showTitle: false,
                    Icon2Name: null,
                    buttonTitle: "회원가입/로그인",
                },
            },
        },
    },
    {
        to: "/login",
        label: "로그인",
        header: {
            byScreen: {
                mobile: { 
                    showLogo: false,
                    showHamburger: false,
                    showBack: true,
                    showNav: false,
                    showTitle: true,
                    Icon2Name: null,
                    buttonTitle: null,
                },
                tablet: { 
                    showLogo: false,
                    showHamburger: false,
                    showBack: true,
                    showNav: false,
                    showTitle: true,
                    Icon2Name: null,
                    buttonTitle: null,
                },
                desktop: { 
                    showLogo: true,
                    showHamburger: false,
                    showBack: false,
                    showNav: false,
                    showTitle: false,
                    Icon2Name: null,
                    buttonTitle: null,
                },
            },
        },
    },
    {
        to: "/myPage",
        label: "마이페이지",
        header: {
            byScreen: {
                mobile: { 
                    showLogo: false,
                    showHamburger: true,
                    showBack: true,
                    showNav: false,
                    showTitle: true,
                    Icon2Name: null,
                    buttonTitle: "회원가입",
                    showButtonTitle: ({ user }) => !user,
                },
                tablet: { 
                    showLogo: false,
                    showHamburger: true,
                    showBack: true,
                    showNav: false,
                    showTitle: true,
                    Icon2Name: null,
                    buttonTitle: "회원가입/로그인",
                    showButtonTitle: ({ user }) => !user,
                },
                desktop: { 
                    showLogo: true,
                    showHamburger: false,
                    showBack: false,
                    showNav: true,
                    showTitle: false,
                    Icon2Name: null,
                    buttonTitle: "회원가입/로그인",
                    showButtonTitle: ({ user }) => !user,
                },
            },
        },
    },
];
  